### ISSUE TITLE
Editing OldUrl creates a duplicate

### ISSUE THREAD

**Issue by m-jedynak** [fortedigital/EpiserverRedirects#23]
1. Create entry for "/foo" -> "/bar" and save it
2. Edit this entry to "/foo2" -> "/bar" and save
3. entry is duplicated

**Comment by w-strzebonski** [comment]
@tomaszmadeyski I think that issue has been resolved. I have repeated all steps and entry is not duplicated.

**Comment by tomaszmadeyski** [comment]
Yes, it seems to be fixed. Closing this one
