### ISSUE TITLE
Replace " " to "%20" when editor pastes url

### ISSUE THREAD

**Issue by m-jedynak** [fortedigital/EpiserverRedirects#25]
If editor enters url with spaces encode it and save in DB in encoded form.

**Comment by tomaszmadeyski** [comment]
@w-strzebonski can this be closed because of #56 ?

**Comment by w-strzebonski** [comment]
@tomaszmadeyski Yes, that can be closed. The issue was also resolved in [#56](https://github.com/fortedigital/EpiserverRedirects/pull/56) so I will close that issue.
