### ISSUE TITLE
Add possibility to export redirects to CSV

### ISSUE THREAD

**Issue by kpkozak** [fortedigital/EpiserverRedirects#42]
I would be beneficial to have possibility to export redirects, review & edit them in Excel and then reimport

**Comment by w-strzebonski** [comment]
@tomaszmadeyski I think that issue is outdated, I mean EpiserverRedirects has already feature, that imports / exports redirects to CSV.

**Comment by tomaszmadeyski** [comment]
@w-strzebonski Import/export option is in place but it does not seem to work properly. I see at least two issues:
- redirect table (in UI) has 11 columns. Exported csv file has 8 columns
- I don't see value of contentId value in exported csv

I didn't test import option but I suspect it might be outdated as well.

**Comment by w-strzebonski** [comment]
@tomaszmadeyski I think the mismatch between number of columns in UI and CSV file is correct,  because user shouldn't edit who created request and the date of creation. Additionally, when CSV is imported, backend automatically assign the date of creation and the user, who imports redirects (the type is also flagged as "Imported"). 

In that issue:
- `ContendId` is now exported
- I fixed bug, that creates mismatch between `ContendId` before and after import.
- Removed unnecessary `MatchToContent` property in `RedirectRuleImportRow.cs`

**Comment by tomaszmadeyski** [comment]
> user shouldn't edit who created request and the date of creation.

I agree but I think we should not think as export/import as 100% coupled operations but rather independent ones. 

**Export:**
Once I export data to csv I would like to know complete picture, who created a rule and when included - I should see exactly same columns as in UI.

**Import**
As you say, I should not be able to specify import date and user during import. So I see two options here:
1. definition of CSV model for import purposes should be different than one from export so it contains only columns which are relevant for import (no date, no user etc). The required import format should be specified somewhere, probably somewhere next to "Import" button in UI
2. definition of CSV model for import and export should be the same but import should ignore values which should not be specified in import (date, user)

Actually the best option is to have combination of both above - so during the process of import we should be able to identify if this CSV contain all columns (like one from export) and then ignore irrelevant or maybe it has only required columns. If neither of those - throw an exception

**Comment by w-strzebonski** [comment]
@tomaszmadeyski From now, all columns from UI table are exported to CSV file. When import is executed, only required columns are obtained from CSV file. Additionally, I added message near "import area" that contains information about required columns to proper import.
