### ISSUE TITLE
Old patterns which contain '+' sign or '%20' are not redirected

### ISSUE THREAD

**Issue by ArcusDeri** [fortedigital/EpiserverRedirects#48]
For example setting Old Pattern to `/TERROR+inaugural+conference+in+Oslo` and New Pattern to `/` results in 404  anyway. The same goes for `/TERROR%20inaugural%20conference%20in%20Oslo`.

**Comment by w-strzebonski** [comment]
@tomaszmadeyski Both problems are related with IIS. In the first case, OldPattern that contains encoded spaces was decoded by IIS when the request is handled and thats why redirect pattern was not found in the db.

In the second case, IIS by default rejects requests which contain url with `+` sign (it is related to security). I changed this behaviour in `Web.config` in `AlloyDemoKit` project for tests but I don't think we should do it. After that change, redirect process with `+` sign works fine.
